language: node_js
node_js:
  - 12.16.1
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod --base-href https://huynhaus.github.io/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/huynhaus
  on:
    branch: master